spring:
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB

  profiles:
    group:
      "dev-profile": "dev,jwt,oauth"
      "prod-profile": "prod,jwt, oauth"
    active: dev-profile


cors:
  allowed-origins: http://localhost:3000
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS,PATCH
  allowed-headers: '*'
  max-age: 3600
